export const properties = {
  example: {
    screen: {
      game: {
        question:
          "Cat ipsum dolor sit amet, meow meow, i tell my human or ask to be pet then attack owners hand. Why dog in house? i'm the sole ruler of this home and its inhabitants smelly, stupid dogs, inferior furballs time for night-hunt, human freakout leave fur on owners clothes. Murf pratt ungow ungow meow meow pee in shoe, or poop on grasses.",
        answer: [
          'Todas as alternativas são verdadeiras.',
          'Apenas I é verdadeira.',
          'Apenas II é verdadeira.',
          'Nenhuma alternativa é verdadeira.',
        ],
      },
      ranking: {
        tableData: [
          {
            name: 'Simon Curry',
            successRate: 64,
            time: '22m10s',
            hits: [
              { i: 1, correct: true },
              { i: 2, correct: true },
              { i: 3, correct: false },
              { i: 4, correct: false },
              { i: 5, correct: true },
              { i: 6, correct: true },
              { i: 7, correct: false },
              { i: 8, correct: true },
              { i: 9, correct: true },
              { i: 10, correct: false },
              { i: 11, correct: true },
              { i: 12, correct: true },
              { i: 13, correct: false },
              { i: 14, correct: true },
            ],
          },
          {
            name: 'Sarah Campbell',
            successRate: 50,
            time: '20m16s',
            hits: [
              { i: 1, correct: false },
              { i: 2, correct: false },
              { i: 3, correct: false },
              { i: 4, correct: false },
              { i: 5, correct: false },
              { i: 6, correct: false },
              { i: 7, correct: false },
              { i: 8, correct: true },
              { i: 9, correct: true },
              { i: 10, correct: true },
              { i: 11, correct: true },
              { i: 12, correct: true },
              { i: 13, correct: true },
              { i: 14, correct: true },
            ],
          },
          {
            name: 'Martha Pratt',
            successRate: 50,
            time: '21m31s',
            hits: [
              { i: 1, correct: false },
              { i: 2, correct: false },
              { i: 3, correct: true },
              { i: 4, correct: true },
              { i: 5, correct: false },
              { i: 6, correct: false },
              { i: 7, correct: true },
              { i: 8, correct: false },
              { i: 9, correct: true },
              { i: 10, correct: true },
              { i: 11, correct: false },
              { i: 12, correct: false },
              { i: 13, correct: true },
              { i: 14, correct: true },
            ],
          },
          {
            name: 'Kelsey Hart',
            successRate: 50,
            time: '22m27s',
            hits: [
              { i: 1, correct: true },
              { i: 2, correct: false },
              { i: 3, correct: true },
              { i: 4, correct: false },
              { i: 5, correct: false },
              { i: 6, correct: false },
              { i: 7, correct: false },
              { i: 8, correct: true },
              { i: 9, correct: false },
              { i: 10, correct: true },
              { i: 11, correct: false },
              { i: 12, correct: true },
              { i: 13, correct: true },
              { i: 14, correct: true },
            ],
          },
          {
            name: 'Jordan Cummings',
            successRate: 50,
            time: '22m50s',
            hits: [
              { i: 1, correct: false },
              { i: 2, correct: true },
              { i: 3, correct: false },
              { i: 4, correct: false },
              { i: 5, correct: false },
              { i: 6, correct: false },
              { i: 7, correct: true },
              { i: 8, correct: true },
              { i: 9, correct: true },
              { i: 10, correct: false },
              { i: 11, correct: true },
              { i: 12, correct: false },
              { i: 13, correct: true },
              { i: 14, correct: true },
            ],
          },
          {
            name: 'Beau Simpson',
            successRate: 50,
            time: '25m18s',
            hits: [
              { i: 1, correct: true },
              { i: 2, correct: true },
              { i: 3, correct: false },
              { i: 4, correct: false },
              { i: 5, correct: true },
              { i: 6, correct: true },
              { i: 7, correct: false },
              { i: 8, correct: false },
              { i: 9, correct: false },
              { i: 10, correct: false },
              { i: 11, correct: false },
              { i: 12, correct: true },
              { i: 13, correct: true },
              { i: 14, correct: true },
            ],
          },
          {
            name: 'Francisco Schultz',
            successRate: 50,
            time: '25m32s',
            hits: [
              { i: 1, correct: false },
              { i: 2, correct: false },
              { i: 3, correct: true },
              { i: 4, correct: true },
              { i: 5, correct: false },
              { i: 6, correct: true },
              { i: 7, correct: false },
              { i: 8, correct: false },
              { i: 9, correct: true },
              { i: 10, correct: false },
              { i: 11, correct: true },
              { i: 12, correct: true },
              { i: 13, correct: true },
              { i: 14, correct: false },
            ],
          },
          {
            name: 'Abby Quinn',
            successRate: 50,
            time: '26m49s',
            hits: [
              { i: 1, correct: false },
              { i: 2, correct: true },
              { i: 3, correct: false },
              { i: 4, correct: true },
              { i: 5, correct: false },
              { i: 6, correct: true },
              { i: 7, correct: true },
              { i: 8, correct: true },
              { i: 9, correct: false },
              { i: 10, correct: false },
              { i: 11, correct: false },
              { i: 12, correct: false },
              { i: 13, correct: true },
              { i: 14, correct: true },
            ],
          },
          {
            name: 'Kira Reid',
            successRate: 50,
            time: '28m14s',
            hits: [
              { i: 1, correct: false },
              { i: 2, correct: false },
              { i: 3, correct: false },
              { i: 4, correct: false },
              { i: 5, correct: false },
              { i: 6, correct: false },
              { i: 7, correct: false },
              { i: 8, correct: true },
              { i: 9, correct: true },
              { i: 10, correct: true },
              { i: 11, correct: true },
              { i: 12, correct: true },
              { i: 13, correct: true },
              { i: 14, correct: true },
            ],
          },
          {
            name: 'Dwayne Neal',
            successRate: 50,
            time: '30m11s',
            hits: [
              { i: 1, correct: false },
              { i: 2, correct: false },
              { i: 3, correct: false },
              { i: 4, correct: false },
              { i: 5, correct: false },
              { i: 6, correct: false },
              { i: 7, correct: false },
              { i: 8, correct: true },
              { i: 9, correct: true },
              { i: 10, correct: true },
              { i: 11, correct: true },
              { i: 12, correct: true },
              { i: 13, correct: true },
              { i: 14, correct: true },
            ],
          },
        ],
      },
    },
  },
  screen: {
    landing: { button: { login: 'Entrar' } },
    menu: {
      button: {
        enterGame: 'Entrar em um jogo',
        seeResults: 'Meus resultados',
        manageQuestions: 'Gerenciar banco de perguntas',
        manageQuizzes: 'Gerenciar questionários',
        logout: 'Sair',
      },
    },
    joinGame: {
      button: { play: 'Jogar', back: 'Voltar' },
      placeholder: { gameCode: 'Insira o código' },
      label: { gameCode: 'Código do quiz' },
    },
    game: {
      button: { confirm: 'Confirmar', next: 'Avançar' },
    },
    ranking: {
      button: { back: 'Voltar' },
      pageHeader: { center: 'Relatório' },
      averagesHeader: {
        hits: 'Média de Acertos',
        time: 'Tempo Médio',
        answers: 'Respostas',
      },
      resultsHeader: {
        place: '#',
        name: 'Nome',
        successRate: 'Acertos',
        time: 'Tempo',
      },
    },
  },
};
